/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-error': '#ffffff',
        'tertiary-fixed-dim': '#ffb3af',
        'on-error-container': '#93000a',
        'primary-container': '#0e71e4',
        'on-primary-container': '#fefcff',
        'secondary-fixed-dim': '#61df70',
        'inverse-primary': '#acc7ff',
        error: '#ba1a1a',
        'surface-container-high': '#e5e8eb',
        'on-secondary': '#ffffff',
        secondary: '#006e24',
        'on-surface': '#181c1e',
        'primary-fixed': '#d7e2ff',
        'surface-container-low': '#f1f4f7',
        'on-tertiary-container': '#fffbff',
        'on-tertiary-fixed': '#410005',
        'surface-tint': '#005cbd',
        'on-surface-variant': '#414754',
        primary: '#0059b9',
        'on-primary-fixed': '#001a40',
        'inverse-surface': '#2d3133',
        'secondary-container': '#7efd89',
        'tertiary-container': '#d43d40',
        'on-secondary-container': '#007526',
        'on-background': '#181c1e',
        'on-primary': '#ffffff',
        background: '#f7fafd',
        'on-tertiary': '#ffffff',
        'error-container': '#ffdad6',
        'on-primary-fixed-variant': '#004591',
        'on-secondary-fixed': '#002106',
        outline: '#727785',
        'surface-dim': '#d7dadd',
        'surface-container': '#ebeef1',
        'tertiary-fixed': '#ffdad7',
        'surface-variant': '#e0e3e6',
        'inverse-on-surface': '#eef1f4',
        'on-secondary-fixed-variant': '#005319',
        'on-tertiary-fixed-variant': '#920418',
        'surface-container-highest': '#e0e3e6',
        'surface-container-lowest': '#ffffff',
        'secondary-fixed': '#7efd89',
        'primary-fixed-dim': '#acc7ff',
        'outline-variant': '#c1c6d6',
        surface: '#f7fafd',
        'surface-bright': '#f7fafd',
        tertiary: '#b1222a',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      gap: {
        gutter: '24px',
        'card-gap': '24px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '600' }],
        'display-metrics': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};

